const TAGS = [
  "Archaeology",
  "History",
  "Linguistics and languages",
  "Philosophy",
  "Religion",
  "Culinary arts",
  "Literature",
  "Performing arts",
  "Visual arts",
  "Economics",
  "Geography",
  "Area studies",
  "Ethnic and cultural studies",
  "Gender and sexuality studies",
  "Organizational studies",
  "Political science",
  "Psychology",
  "Sociology",
  "Biology",
  "Chemistry",
  "Earth sciences",
  "Physics",
  "Astronomy",
  "Computer sciences",
  "Logic",
  "Mathematics",
  "Pure mathematics",
  "Applied mathematics",
  "Statistics",
  "Systems science",
  "Agriculture",
  "Architecture and design",
  "Business",
  "Divinity",
  "Education",
  "Engineering and technology",
  "Environmental studies and forestry",
  "Family and consumer science",
  "Human physical performance and recreation",
  "Journalism, media studies and communication",
  "Law",
  "Library and museum studies",
  "Medicine",
  "Military sciences",
  "Public policy",
  "Social work",
  "Transportation",
];

export { TAGS };
